
from typing import Tuple

class ContentCleanPrompt:
    systemp_prompt:Tuple[str] = (
        "You are a content refinement assistant specialized in cleaning and extracting meaningful information from unstructured business listings scraped from the web.\n"
        "Your job is to remove all irrelevant content such as page navigation elements, site footers, repeated boilerplate text, advertisements, cookie notices, and layout instructions.\n"
        "Focus only on preserving business-specific content such as the business description, location, pricing, revenue, net profit, tenure, and any other commercial or operational information.\n"
        "Do not summarize or rewrite — simply clean the content to keep only what is contextually relevant to a business listing.")

    user_prompt:Tuple[str] = (
        "The following is raw text scraped from a business listing. It contains both valuable business information and irrelevant website noise.\n\n"
        "Your task is to clean this content. Specifically:\n"
        "- Remove irrelevant elements such as:\n"
        "  - Navigation menus (e.g., \"Home\", \"Back to Search\", \"Choose your country\", etc.)\n"
        "  - UI controls and buttons (e.g., \"Print\", \"Share\", \"Save\", \"Request Info\")\n"
        "  - Cookie notices, loading messages, repetitive headers/footers\n"
        "  - Visual formatting artifacts or layout instructions (e.g., \"top of page\", \"loading...\")\n\n"
        "- Keep all relevant business-related information including:\n"
        "  - Business name and headline\n"
        "  - Descriptions of the business and services\n"
        "  - Key financial metrics (asking price, turnover, net profit, rent, franchise fee, etc.)\n"
        "  - Tenure details (freehold/leasehold, lease terms)\n"
        "  - Business location\n"
        "  - Unique selling points, differentiators\n"
        "  - Awards, recognitions, testimonials\n"
        "  - Ideal operator/franchisee profiles\n"
        "  - Lifestyle details (e.g., home-based, relocatable)\n\n"
        "Do not paraphrase, summarize or add any commentary — just return the cleaned business listing text with all irrelevant parts removed.\n\n"
        "### Raw Listing Text:\n"
        "\"\"\"\n"
        "{content}\n"
        "\"\"\"") 
    
class InformationExtractionPrompt:
    system_prompt:Tuple[str] = (
        "You are a highly skilled investment analyst helping an investor evaluate business listings. "
        "The investor has up to £250,000 available and is only interested in commercially viable businesses that offer a proportionate return on that capital. "
        "You must apply professional investment logic and critical thinking. A business with extremely low profit (e.g., under £5,000–10,000/year) will almost never be suitable for this level of investment unless there is strong strategic or high-growth potential explicitly stated. "
        "Do not make assumptions. Base your evaluation strictly on available figures. If the business does not clearly justify the capital, mark it as a poor investment.")
    

    user_prompt:Tuple[str] = (
        "Extract structured business information from the listing below.\n\n"
        "Return a single JSON object. If any field is not clearly stated, write \"No Info Available\". Do not infer or assume data.\n\n"
        "Fields to extract:\n"
        "- Location (City or Region)\n"
        "- Post Code\n"
        "- Type (Online / Physical store / Hybrid)\n"
        "- Asking price\n"
        "- Turnover\n"
        "- Net profit\n"
        "- Franchise (Yes / No)\n"
        "- Business type (e.g., café, car wash, consultancy, e-commerce, etc.)\n"
        "- Annual rent (if applicable)\n"
        "- Tenure (Leasehold / Freehold / Not specified)\n"
        "- Lease length (if applicable)\n"
        "- Lease years remaining (if applicable)\n"
        "- Years established\n"
        "- Number of employees\n"
        "- Home based (Yes / No)\n"
        "- Relocatable (Yes / No)\n"
        "- Additional notes (include any relevant information not captured above)\n\n"
        "Initial analysis:\n"
        "- Provide a short, commercially realistic assessment based on the investor’s capital (£250,000).\n"
        "- Explicitly assess whether the business is worth considering for this level of investment. "
        "A business generating very low annual profit (e.g., under £10,000) is unlikely to meet minimum return expectations and should be flagged accordingly.\n"
        "- Use investment logic: Consider asking price relative to net profit and capital. Consider time-to-ROI. "
        "If the return is insignificant relative to capital, state that clearly.\n\n"
        "Recommendation:\n"
        "- \"Shortlist\" — only if the business offers realistic ROI for the capital level.\n"
        "- \"Leave\" — if the profit or opportunity is not commercially attractive for a £250,000 investor.\n\n"
        "Your response must be a valid, clean JSON object only. Do not include markdown, commentary, or code block syntax. Do not wrap it in triple quotes.\n\n"
        "Example format:\n"
        "{{\n"
        "  \"Location\": \"\",\n"
        "  \"Post Code\": \"\",\n"
        "  \"Type\": \"\",\n"
        "  \"Asking price\": \"\",\n"
        "  \"Turnover\": \"\",\n"
        "  \"Net profit\": \"\",\n"
        "  \"Franchise\": \"\",\n"
        "  \"Business type\": \"\",\n"
        "  \"Annual rent\": \"\",\n"
        "  \"Tenure\": \"\",\n"
        "  \"Lease length\": \"\",\n"
        "  \"Lease years remaining\": \"\",\n"
        "  \"Years established\": \"\",\n"
        "  \"Number of employees\": \"\",\n"
        "  \"Home based\": \"\",\n"
        "  \"Relocatable\": \"\",\n"
        "  \"Additional notes\": \"\",\n"
        "  \"Initial analysis\": \"\",\n"
        "  \"Recommendation\": \"\"\n"
        "}}\n\n"
        "Business Listing Content:\n"
        "\"\"\"\n"
        "{content}\n"
        "\"\"\"")
